# Generated by Django 5.1.3 on 2025-08-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RADICAL', 'Radical'), ('KANJI', 'Kanji'), ('VOCAB', 'Vocab')], max_length=10)),
                ('literal', models.CharField(help_text='The character or string (e.g. 水, 食べる)', max_length=10)),
                ('meaning', models.CharField(max_length=255)),
                ('reading', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.PositiveIntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('constituents', models.ManyToManyField(blank=True, related_name='used_in', to='kanjilearner.dictionaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='UserDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('srs_stage', models.CharField(choices=[('A1', 'Apprentice 1'), ('A2', 'Apprentice 2'), ('A3', 'Apprentice 3'), ('A4', 'Apprentice 4'), ('G1', 'Guru 1'), ('G2', 'Guru 2'), ('M', 'Master'), ('E', 'Enlightened'), ('B', 'Burned')], default='A1', max_length=2)),
                ('user_synonyms', models.JSONField(blank=True, default=list)),
                ('user_sentences', models.JSONField(blank=True, default=list)),
                ('review_history', models.JSONField(blank=True, default=list)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanjilearner.dictionaryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
