# Generated by Django 5.1.3 on 2025-08-16 02:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RADICAL', 'Radical'), ('KANJI', 'Kanji'), ('VOCAB', 'Vocab')], max_length=10)),
                ('literal', models.CharField(help_text='The character or string (e.g. 水, 食べる)', max_length=10)),
                ('meaning', models.CharField(max_length=255)),
                ('kunyomi_readings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('onyomi_readings', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('level', models.PositiveIntegerField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('reading_mnemonic', models.TextField(blank=True, help_text='Explanation to help remember the reading')),
                ('meaning_mnemonic', models.TextField(blank=True, help_text='Explanation to help remember the meaning')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Ordering within a level')),
                ('parts_of_speech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('noun', 'Noun'), ('transitive_verb', 'Transitive Verb'), ('intransitive_verb', 'Intransitive Verb'), ('i_adj', 'い-Adjective'), ('na_adj', 'な-Adjective'), ('suru_noun', 'する-Noun'), ('adverb', 'Adverb'), ('expression', 'Expression'), ('conjunction', 'Conjunction'), ('prefix', 'Prefix'), ('suffix', 'Suffix')], max_length=30), blank=True, default=list, help_text='Multiple parts of speech allowed (e.g. noun, suru_noun)', size=None)),
                ('constituents', models.ManyToManyField(blank=True, related_name='used_in', to='kanjilearner.dictionaryentry')),
            ],
            options={
                'ordering': ['level', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='UserDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('srs_stage', models.CharField(choices=[('L', 'Lesson'), ('A1', 'Apprentice 1'), ('A2', 'Apprentice 2'), ('A3', 'Apprentice 3'), ('A4', 'Apprentice 4'), ('G1', 'Guru 1'), ('G2', 'Guru 2'), ('M', 'Master'), ('E', 'Enlightened'), ('B', 'Burned')], default='L', max_length=2)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_history', models.JSONField(blank=True, default=list)),
                ('user_synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('user_sentences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanjilearner.dictionaryentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dictionaryentry',
            constraint=models.UniqueConstraint(fields=('level', 'priority'), name='unique_priority_per_level'),
        ),
    ]
