# Generated by Django 5.1.3 on 2025-08-16 05:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explain the definition in context and reading distinctions if multiple readings exist.'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='readings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Kana readings for vocab (e.g. たべる, みず)', size=None),
        ),
    ]
