# Generated by Django 5.1.3 on 2025-08-15 23:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='reading',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='kunyomi_readings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='onyomi_readings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
