# Generated by Django 5.1.3 on 2025-08-16 05:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0002_dictionaryentry_explanation_dictionaryentry_readings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='parts_of_speech',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('noun', 'Noun'), ('suru_noun', 'する-Noun'), ('i_adj', 'い-Adjective'), ('na_adj', 'な-Adjective'), ('godan_verb', 'Godan Verb (五段動詞)'), ('ichidan_verb', 'Ichidan Verb (一段動詞)'), ('transitive_verb', 'Transitive Verb'), ('intransitive_verb', 'Intransitive Verb'), ('adverb', 'Adverb'), ('expression', 'Expression'), ('conjunction', 'Conjunction'), ('prefix', 'Prefix'), ('suffix', 'Suffix')], max_length=30), blank=True, default=list, help_text='Multiple parts of speech allowed (e.g. noun, suru_noun)', size=None),
        ),
    ]
