# Generated by Django 5.1.3 on 2025-08-16 00:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0002_remove_dictionaryentry_reading_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['level', 'priority']},
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='parts_of_speech',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('noun', 'Noun'), ('transitive_verb', 'Transitive Verb'), ('intransitive_verb', 'Intransitive Verb'), ('i_adj', 'い-Adjective'), ('na_adj', 'な-Adjective'), ('suru_noun', 'する-Noun'), ('adverb', 'Adverb'), ('expression', 'Expression'), ('conjunction', 'Conjunction'), ('prefix', 'Prefix'), ('suffix', 'Suffix')], max_length=30), blank=True, default=list, help_text='Multiple parts of speech allowed (e.g. noun, suru_noun)', size=None),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Ordering within a level'),
        )
    ]
