# Generated by Django 5.1.3 on 2025-08-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0003_alter_dictionaryentry_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dictionaryentry',
            constraint=models.UniqueConstraint(fields=('level', 'priority'), name='unique_priority_per_level'),
        ),
    ]
