# Generated by Django 5.1.3 on 2025-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0003_alter_dictionaryentry_parts_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaryentry',
            name='srs_stage',
            field=models.CharField(choices=[('INIT', 'Locked'), ('L', 'Lesson'), ('A1', 'Apprentice 1'), ('A2', 'Apprentice 2'), ('A3', 'Apprentice 3'), ('A4', 'Apprentice 4'), ('G1', 'Guru 1'), ('G2', 'Guru 2'), ('M', 'Master'), ('E', 'Enlightened'), ('B', 'Burned')], default='L', max_length=30),
        ),
    ]
