# Generated by Django 5.1.3 on 2025-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0004_alter_userdictionaryentry_srs_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaryentry',
            name='srs_stage',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('LESSON', 'Lesson'), ('APPRENTICE_1', 'Apprentice 1'), ('APPRENTICE_2', 'Apprentice 2'), ('APPRENTICE_3', 'Apprentice 3'), ('APPRENTICE_4', 'Apprentice 4'), ('GURU_1', 'Guru 1'), ('GURU_2', 'Guru 2'), ('MASTER', 'Master'), ('ENLIGHTENED', 'Enlightened'), ('BURNED', 'Burned')], default='LOCKED', max_length=30),
        ),
    ]
