# Generated by Django 5.1.3 on 2025-08-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0006_fix_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdictionaryentry',
            name='unlocked',
        ),
    ]
