# Generated by Django 5.1.3 on 2025-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0008_recentmistake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='type',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='entry_type',
            field=models.CharField(choices=[('RADICAL', 'Radical'), ('KANJI', 'Kanji'), ('VOCAB', 'Vocabulary')], default='KANJI', max_length=10),
        ),
    ]
