# Generated by Django 5.1.3 on 2025-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0009_remove_dictionaryentry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='entry_type',
            field=models.CharField(choices=[('RADICAL', 'Radical'), ('KANJI', 'Kanji'), ('VOCAB', 'Vocabulary')], default='RADICAL', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='dictionaryentry',
            constraint=models.CheckConstraint(condition=models.Q(('entry_type__in', ['RADICAL', 'KANJI', 'VOCAB'])), name='valid_entry_type_only'),
        ),
    ]
