# Generated by Django 5.1.3 on 2025-09-22 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0011_plannedentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionaryentry',
            options={'ordering': ['level']},
        ),
        migrations.RemoveConstraint(
            model_name='dictionaryentry',
            name='unique_priority_per_level',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='priority',
        ),
    ]
