# Generated by Django 5.1.3 on 2025-09-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0012_alter_dictionaryentry_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dictionaryentry',
            constraint=models.UniqueConstraint(condition=models.Q(('literal', ''), _negated=True), fields=('literal', 'entry_type'), name='unique_literal_entrytype'),
        ),
    ]
