# Generated by Django 5.1.3 on 2025-09-25 23:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanjilearner', '0013_dictionaryentry_unique_literal_entrytype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dictionaryentry',
            name='unique_literal_entrytype',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='readings',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='pitch_graphs',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('H', 'High'), ('L', 'Low'), ('(L)', 'DropLow')], max_length=3), size=None), blank=True, default=list, help_text='For vocab only: pitch accent graphs (one per reading if needed).', size=None),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='reading',
            field=models.CharField(blank=True, help_text='Kana readings for vocab (e.g. たべる, みず)', max_length=50),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='used_in',
            field=models.ManyToManyField(blank=True, help_text='For radicals → kanji they appear in; for kanji → vocab they appear in', related_name='+', to='kanjilearner.dictionaryentry'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='visually_similar',
            field=models.ManyToManyField(blank=True, help_text='Visually similar kanji, vocab, or radicals (not automatically reciprocal)', to='kanjilearner.dictionaryentry'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='constituents',
            field=models.ManyToManyField(blank=True, related_name='+', to='kanjilearner.dictionaryentry'),
        ),
    ]
